name: GitHub-Profile-Summary-Cards

on:
  push:
    branches: [ main, master ]
  schedule: # execute every 24 hours
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate GitHub Profile Summary Cards
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.profile-summary-cards-token }}

      - name: Generate GitHub Profile Summary Cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.profile-summary-cards-token }}
        with:
          USERNAME: ${{ github.repository_owner }}

      - name: Commit and push generated cards
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update GitHub profile summary cards" || exit 0
          git push
